config/routes.rb
Tutorial::Application.routes.draw do
  resources :forthreads

  resources :posts

  resources :users

end

app/models/forthread.rb
class Forthread < ActiveRecord::Base
	belongs_to :user
	has_many :posts
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
	belongs_to :forthread
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :posts
	has_many :forthreads
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/forthreads_controller.rb
class ForthreadsController < ApplicationController
  before_action :set_forthread, only: [:show, :edit, :update, :destroy]

  # GET /forthreads
  # GET /forthreads.json
  def index
    @forthreads = Forthread.all
  end

  # GET /forthreads/1
  # GET /forthreads/1.json
  def show
  end

  # GET /forthreads/new
  def new
    @forthread = Forthread.new
    @users = User.find :all
  end

  # GET /forthreads/1/edit
  def edit
    @users = User.find :all
  end

  # POST /forthreads
  # POST /forthreads.json
  def create
    @forthread = Forthread.new(forthread_params)

    respond_to do |format|
      if @forthread.save
        format.html { redirect_to @forthread, notice: 'Forum thread was successfully created.' }
        format.json { render action: 'show', status: :created, location: @forthread }
      else
        @users = User.find :all
        format.html { render action: 'new' }
        format.json { render json: @forthread.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /forthreads/1
  # PATCH/PUT /forthreads/1.json
  def update
    respond_to do |format|
      if @forthread.update(forthread_params)
        format.html { redirect_to @forthread, notice: 'Forum thread was successfully updated.' }
        format.json { head :no_content }
      else
        @users = User.find :all
        format.html { render action: 'edit' }
        format.json { render json: @forthread.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /forthreads/1
  # DELETE /forthreads/1.json
  def destroy
    @forthread.transaction do
      @threadPosts = Post.where(forthread_id: @forthread.id)
      @threadPosts.each do |post|
        post.destroy!
      end
      @forthread.destroy!
    end
    respond_to do |format|
      format.html { redirect_to forthreads_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_forthread
      @forthread = Forthread.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def forthread_params
      params.require(:forthread).permit(:title, :user_id)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
    @forthreads = Forthread.find :all
    @users = User.find :all
  end

  # GET /posts/1/edit
  def edit
    @forthreads = Forthread.find :all
    @users = User.find :all
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render action: 'show', status: :created, location: @post }
      else
        @forthreads = Forthread.find :all
        @users = User.find :all
        format.html { render action: 'new' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        @forthreads = Forthread.find :all
        @users = User.find :all
        format.html { render action: 'edit' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:forthread_id, :message, :user_id, :location_place)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.transaction do
      @userThreads = Forthread.where(user_id: @user.id)
      @userThreads.each do |thread|
        @threadPosts = Post.where(forthread_id: thread.id)
        @threadPosts.each do |post|
          post.destroy!
        end
        thread.destroy!
      end

      @userPosts = Post.where(user_id: @user.id)
      @userPosts.each do |post|
        post.destroy!
      end
      @user.destroy!
    end
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:login, :password, :city, :age, :gender)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/forthreads_helper.rb
module ForthreadsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/forthreads/_form.html.erb
<%= form_for(@forthread) do |f| %>
  <% if @forthread.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@forthread.errors.count, "error") %> prohibited this forthread from being saved:</h2>

      <ul>
      <% @forthread.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= collection_select(:forthread,:user_id,@users,:id,:login) %></p>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/forthreads/edit.html.erb
<h1>Editing forthread</h1>

<%= render 'form' %>

<%= link_to 'Show', @forthread %> |
<%= link_to 'Back', forthreads_path %>

app/views/forthreads/index.html.erb
<h1>Listing forum threads</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>User</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @forthreads.each do |forthread| %>
      <tr>
        <td><%= forthread.title %></td>
        <td><%= forthread.user.login %></td>
        <td><%= link_to 'Show', forthread %></td>
        <td><%= link_to 'Edit', edit_forthread_path(forthread) %></td>
        <td><%= link_to 'Destroy', forthread, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New forum thread', new_forthread_path %>

app/views/forthreads/new.html.erb
<h1>New forum thread</h1>

<%= render 'form' %>

<%= link_to 'Back', forthreads_path %>

app/views/forthreads/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @forthread.title %>
</p>

<p>
  <strong>User:</strong>
  <%= @forthread.user.login %>
</p>

<%= link_to 'Edit', edit_forthread_path(@forthread) %> |
<%= link_to 'Back', forthreads_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tutorial</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :forthread_id %><br>
    <%= collection_select(:post,:forthread_id,@forthreads,:id,:title) %>
  </div>
  <div class="field">
    <%= f.label :message %><br>
    <%= f.text_area :message %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= collection_select(:post,:user_id,@users,:id,:login) %>
  </div>
  <div class="field">
    <%= f.label :location_place %><br>
    <%= f.text_field :location_place %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Listing posts</h1>

<table>
  <thead>
    <tr>
      <th>Forum thread</th>
      <th>Message</th>
      <th>User</th>
      <th>Location place</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.forthread.title %></td>
        <td><%= post.message %></td>
        <td><%= post.user.login %></td>
        <td><%= post.location_place %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Forum thread:</strong>
  <%= @post.forthread.title %>
</p>

<p>
  <strong>Message:</strong>
  <%= @post.message %>
</p>

<p>
  <strong>User:</strong>
  <%= @post.user.login %>
</p>

<p>
  <strong>Location place:</strong>
  <%= @post.location_place %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :login %><br>
    <%= f.text_field :login %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :age %><br>
    <%= f.number_field :age %>
  </div>
  <div class="field">
    <%= f.label :gender %><br>
    <%= select(:user, :gender, [['Male', 'Male'], ['Female', 'Female']]) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Login</th>
      <th>Password</th>
      <th>City</th>
      <th>Age</th>
      <th>Gender</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.login %></td>
        <td><%= user.password %></td>
        <td><%= user.city %></td>
        <td><%= user.age %></td>
        <td><%= user.gender %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Login:</strong>
  <%= @user.login %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<p>
  <strong>City:</strong>
  <%= @user.city %>
</p>

<p>
  <strong>Age:</strong>
  <%= @user.age %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @user.gender %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>